apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "haproxy.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "haproxy.fullname" . }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "haproxy.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      affinity:
      {{- if .Values.affinity }}
      {{- if .Values.affinity.nodeAffinity }}
        nodeAffinity:
{{ toYaml .Values.affinity.nodeAffinity | indent 8 }}      
      {{- end }}
      {{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: {{ template "haproxy.fullname" . }}
                release: {{ .Release.Name }}
            namespaces:
            - {{ .Release.Namespace }}
            {{- if .Values.topologyKey }}
            topologyKey: {{ .Values.topologyKey }}
            {{- end }}
      containers:
      - args:
        - haproxy
        - -f
        - /usr/local/etc/haproxy/haproxy.cfg
        env:
        - name: Pod_Name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: Pod_Namespace
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        livenessProbe:
          tcpSocket:
            port: 1235
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 1235
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/
          name: haproxy-conf
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
     {{- if .Values.restartPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- end }}
      {{- if .Values.tolerations }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
     {{- end }}
     {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: haproxy.cfg
            path: haproxy.cfg
          name: {{ .Release.Name }}-conf
        name: haproxy-conf
