apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "haproxy.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/service-type: "headless-service"
  name: {{ .Release.Name }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: port
      port: 1235
      protocol: TCP
      targetPort: 1235
  selector:
    app: {{ template "haproxy.fullname" . }}
    release: {{ .Release.Name }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "haproxy.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/service-type: "headless-service"
  name: {{ .Release.Name }}-redis-headless
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port
      port: 16379
      protocol: TCP
      targetPort: 16379
  selector:
    app: {{ template "haproxy.fullname" . }}
    release: {{ .Release.Name }}
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "haproxy.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/service-type: "nodeport-service"
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: port
      {{- if .Values.svc }}
      {{- if .Values.svc.nodePort }}
      nodePort: {{ .Values.svc.nodePort }}
      {{- end }}
      {{- end }}
      port: 1235
      protocol: TCP
      targetPort: 1235
  selector:
    app: {{ template "haproxy.fullname" . }}
    release: {{ .Release.Name }}
  type: NodePort
