##---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-harbor-registry"
  labels:
    heritage: Tiller
    release: harbor
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTTP_SECRET: "NVBqdmIyTXVUUmxmM09kdQ=="
  REGISTRY_REDIS_PASSWORD: ""
  REGISTRY_STORAGE_S3_ACCESSKEY: "aGFyYm9yczM="
  REGISTRY_STORAGE_S3_SECRETKEY: "aGFyYm9yczM="
